Update to new Version
zenml-io/zenfiles pull request #31
Opened 2022-05-10 09:10 UTC by ayush714

Made compatible with latest version.

2022-05-11 12:04 UTC, AlexejPenner commented
Hey Ayush, what exatcly was the task for this PR - upgrading the zenfile to how mlflow is used in 0.7.3? Would be good to give a little bit of context in the PR description

2022-05-11 12:06 UTC, ayush714 commented
> Hey Ayush, what exatcly was the task for this PR - upgrading the zenfile to how mlflow is used in 0.7.3? Would be good to give a little bit of context in the PR description

Yes @AlexejPenner

2022-05-12 10:11 UTC, ayush714 commented
In `streamlit_app.py` I implemented that functionality, it will work fine but in my system I am getting some dependency error.

2022-05-12 10:18 UTC, AlexejPenner requested changes
Just a tiny wording that I had a suggestion on, other than that this looks good to me

2022-05-12 10:18 UTC, AlexejPenner commented on customer-satisfaction/streamlit_app.py
> +            st.write("The service is not there, Running the pipeline first to create service.")
```suggestion
            st.write("No service could be found. The pipeline will be run first to create a service.")
```

2022-05-12 10:25 UTC, ayush714 commented on customer-satisfaction/streamlit_app.py
> +            st.write("The service is not there, Running the pipeline first to create service.")
Sure, thx

2022-05-16 10:13 UTC, AlexejPenner approved these changes
LGTM

2022-05-16 10:15 UTC, merged