Update Customer Churn ZenFile to ZenML 0.20.2
zenml-io/zenfiles pull request #45
Opened 2022-10-13 09:38 UTC by safoinme

## Describe changes
Update the Custom Churn ZenFile to work with ZenML 0.20.2!

## Pre-requisites
Please ensure you have done the following:
- [X] If my change requires a change to docs, I have updated the documentation accordingly.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Other (add details above)

2022-10-17 11:31 UTC, AlexejPenner requested changes
Two small improverments, otherwise looks good

2022-10-17 11:31 UTC, AlexejPenner commented on customer-churn/README.md
> +### Run the pipeline on a local orchestrator Pipelines deployment
```suggestion
### Run the pipeline on a local orchestrator
```

2022-10-17 11:31 UTC, AlexejPenner commented on customer-churn/README.md
> +2. (Optional) 🎨 Customize your deployment by editing the default values in the `locals.tf` file.
You could write one sentece explaining what this does

2022-10-18 08:21 UTC, htahir1 requested changes
Left a quick review

2022-10-18 08:21 UTC, htahir1 commented on customer-churn/README.md
> +zenml integration install -y facets sklearn xgboost lightgbm kubeflow seldon
-y at the end

2022-10-18 08:21 UTC, htahir1 commented on customer-churn/README.md
> +## Deploy pipelines to production using orchestrator Pipelines
not sure if this is the right change?

2022-10-18 08:21 UTC, htahir1 commented on customer-churn/README.md
> +    zenml secret register aws_rds_secret \
Do we need the rds secret now? I dont think so

2022-10-26 07:22 UTC, merged